---
title: "Optimization Practice"
author: "Will Townes"
date: "11/15/2017"
output: html_document
---

```{r}
library(ggplot2)
```

### Define Algorithms

```{r}
MAXITER<-2000
grad_descent<-function(f,g,x_init,stp=.001,maxIter=MAXITER){
  delta<-100
  t<-1
  res<-matrix(0,nrow=maxIter,ncol=3)
  colnames(res)<-c("x","y","f")
  res[1,]<-c(x_init,f(x_init))
  while(abs(delta)>1e-6 && t<maxIter){
    t<-t+1
    grad<-g(res[t-1,1:2])
    res[t,1:2]<-res[t-1,1:2]-stp*grad
    res[t,3]<-f(res[t,1:2])
    delta<-res[t,3]-res[t-1,3]
  }
  as.data.frame(res[1:t,])
}

momentum<-function(f,g,x_init,stp=.001,maxIter=MAXITER,momentum=.9,wait=1){
  delta<-100
  t<-1
  res<-matrix(0,nrow=maxIter,ncol=3)
  colnames(res)<-c("x","y","f")
  res[1,]<-c(x_init,f(x_init))
  velo<-0
  while(abs(delta)>1e-6 && t<maxIter){
    t<-t+1
    if(t<wait) velo<-0
    velo<-momentum*velo
    grad<-g(res[t-1,1:2])
    velo<-velo+stp*grad
    res[t,1:2]<-res[t-1,1:2]-velo
    res[t,3]<-f(res[t,1:2])
    delta<-res[t,3]-res[t-1,3]
  }
  as.data.frame(res[1:t,])
}

nesterov<-function(f,g,x_init,stp=.001,maxIter=MAXITER,momentum=.9,wait=1){
  delta<-100
  t<-1
  res<-matrix(0,nrow=maxIter,ncol=3)
  colnames(res)<-c("x","y","f")
  res[1,]<-c(x_init,f(x_init))
  velo<-0
  while(abs(delta)>1e-6 && t<maxIter){
    t<-t+1
    if(t<wait) velo<-0
    velo<-momentum*velo
    grad<-g(res[t-1,1:2]-velo)
    velo<-velo+stp*grad
    res[t,1:2]<-res[t-1,1:2]-velo
    res[t,3]<-f(res[t,1:2])
    delta<-res[t,3]-res[t-1,3]
  }
  as.data.frame(res[1:t,])
}

irprop<-function(f,g,x_init,maxIter=MAXITER,eta_plus=1.2,eta_minus=.5,
                 delta_max=50,delta_min=0,delta0=.5){
  k<-length(x_init)
  chg<-100
  t<-1
  res<-matrix(0,nrow=maxIter,ncol=3)
  colnames(res)<-c("x","y","f")
  res[1,]<-c(x_init,f(x_init))
  delta_old<-delta<-delta0*rep(1,k)
  dw<-grad_old<-rep(0,k)
  while(abs(chg)>1e-6 && t<maxIter){
  #while(t<maxIter){
    grad<-g(res[t,1:k])
    ind<-sign(grad_old)*sign(grad)
    delta[ind>0]<-min(delta_old[ind>0]*eta_plus, delta_max)
    delta[ind<0]<-max(delta_old[ind<0]*eta_minus, delta_min)
    grad[ind<0]<-1e-4*grad[ind<0] #comment out this line to get "original" rprop
    
    #irprop+
    #dw[ind>=0]<- -sign(grad[ind>=0])*delta[ind>=0]
    #dw[ind<0]<- if(chg>0) -dw[ind<0] else 0
    #irprop-
    dw<- -sign(grad)*delta
    
    res[t+1,1:k]<-res[t,1:k]+dw
    res[t+1,k+1]<-f(res[t+1,1:k])
    chg<-res[t+1,k+1]-res[t,k+1]
    delta_old<-delta
    grad_old<-grad
    t<-t+1
  }
  as.data.frame(res[1:t,])
}

adamax<-function(f,g,x_init,maxIter=MAXITER,stp=.002,
                 beta1=.9,beta2=.999){
  k<-length(x_init)
  chg<-100
  t<-1
  res<-matrix(0,nrow=maxIter,ncol=3)
  colnames(res)<-c("x","y","f")
  res[1,]<-c(x_init,f(x_init))
  m<-rep(0,k)
  u<-rep(0,k)
  while(abs(chg)>1e-6 && t<maxIter){
    t<-t+1
    grad<-g(res[t-1,1:k])
    m<-beta1*m+(1-beta1)*grad
    u<-pmax(beta2*u,abs(grad))
    velo<- -(stp/(1-beta1^t))*m/u
    res[t,1:k]<-res[t-1,1:k]+velo
    res[t,k+1]<-f(res[t,1:k])
    chg<-res[t,k+1]-res[t-1,k+1]
  }
  as.data.frame(res[1:t,])
}

nadam<-function(f,g,x_init,maxIter=MAXITER,stp=.002,
                 beta1=.9,beta2=.999){
  k<-length(x_init)
  chg<-100
  t<-1
  res<-matrix(0,nrow=maxIter,ncol=3)
  colnames(res)<-c("x","y","f")
  res[1,]<-c(x_init,f(x_init))
  m<-rep(0,k)
  u<-rep(0,k)
  while(abs(chg)>1e-6 && t<maxIter){
    t<-t+1
    grad<-g(res[t-1,1:k])
    m<-beta1*m+(1-beta1)*grad
    u<-pmax(beta2*u,abs(grad))
    velo<- -(stp/u)*(beta1*m+grad*(1-beta1))/(1-beta1^t)
    res[t,1:k]<-res[t-1,1:k]+velo
    res[t,k+1]<-f(res[t,1:k])
    chg<-res[t,k+1]-res[t-1,k+1]
  }
  as.data.frame(res[1:t,])
}
```

### Rosenbrock function, minimum is at (1,1)

```{r}
rosenbrock_f <- function(x){
  (1-x[1])^2 + 10*(x[2]-x[1]^2)^2
}
rosenbrock_g <- function(x){
  dx1<- -2*(1-x[1]) - 20*(x[2]-x[1]^2)*2*x[1]
  dx2<- 20*(x[2]-x[1]^2)
  c(dx1,dx2)
}
solution<-data.frame(x=1,y=1)

pd<-expand.grid(x=seq(-3,3,.01),y=seq(0,6,.01))
pd$z<-apply(pd,1,rosenbrock_f)
ggplot(pd,aes(x=x,y=y))+geom_raster(aes(fill=log1p(z)))+scale_fill_continuous(low="red",high="blue")
(base_plot<-ggplot(pd)+geom_contour(aes(x=x,y=y,z=log1p(z)))+geom_point(data=solution,aes(x,y),colour="red",size=10,shape="x"))
```

simple gradient descent

```{r}
res<-list()
res[["gd"]]<-grad_descent(rosenbrock_f,rosenbrock_g,c(3,5))
base_plot+geom_path(aes(x=x,y=y),data=res$gd)
```

gradient descent with momentum

```{r}
res[["mtm"]]<-momentum(rosenbrock_f,rosenbrock_g,c(3,5),stp=.002)
base_plot+geom_path(data=res$mtm,aes(x,y))
```

gradient descent with Nesterov momentum

```{r}
res[["nstv"]]<-nesterov(rosenbrock_f,rosenbrock_g,c(3,5),stp=.002)
base_plot+geom_path(data=res$nstv,aes(x,y))
```

improved rprop

```{r}
res[["irprop"]]<-irprop(rosenbrock_f,rosenbrock_g,c(3,5))
base_plot+geom_path(data=res$irprop,aes(x,y))
#with(tail(res$irprop,20),plot(x,y,type="l"))
```

adamax- Adam with infinity norm

```{r}
res[["admx"]]<-adamax(rosenbrock_f,rosenbrock_g,c(3,5),stp=3)
base_plot+geom_path(data=res$admx,aes(x,y))
#with(tail(res$admx,500),plot(x,y,type="l"))
```

nadam- Adam with nesterov momentum

```{r}
res[["nadm"]]<-nadam(rosenbrock_f,rosenbrock_g,c(3,5),stp=3)
base_plot+geom_path(data=res$nadm,aes(x,y))
#with(tail(res$admx,500),plot(x,y,type="l"))
```

summary of results

```{r}
pd2<-data.frame(method=names(res),nSteps=sapply(res,nrow))
pd2$err<-sapply(res,function(x){x[nrow(x),3]})
ggplot(pd2)+geom_bar(aes(x=method,y=log(err)),stat="identity")
ggplot(pd2)+geom_bar(aes(x=method,y=nSteps),stat="identity")
```