---
title: "Rosenbrock function benchmarking"
author: "Will Townes"
output: html_document
---

```{r}
library(ggplot2)
pth<-"plots/rosenbrock"
if(!dir.exists(pth)){ dir.create(pth,recursive=TRUE) }
ggs<-function(x,w=6,h=4){
  ggsave(file=file.path(pth,paste0(x,".pdf")),width=w,height=h)
}
source("./algorithms.R")
```

### Rosenbrock function, minimum is at (1,1)

```{r}
rosenbrock_f <- function(x,a=1,b=10){
  (a-x[1])^2 + b*(x[2]-x[1]^2)^2
}
rosenbrock_g <- function(x,a=1,b=10){
  dx1<- -2*(a-x[1]) - 2*b*(x[2]-x[1]^2)*2*x[1]
  dx2<- 2*b*(x[2]-x[1]^2)
  c(dx1,dx2)
}
rosenbrock_h <- function(x,a=1,b=10){
  h11<- 2-4*b*x[2]+12*b*x[1]^2
  h12<- -4*b*x[1]
  h22<- 2*b
  matrix(c(h11,h12,h12,h22),nrow=2)
}
solution<-data.frame(x=1,y=1)

xlo<- -4; xhi<- 4; ylo<- -3; yhi<-12
pd<-expand.grid(x=seq(xlo,xhi,.04),y=seq(ylo,yhi,.04))
pd$z<-apply(pd,1,rosenbrock_f)
ggplot(pd,aes(x=x,y=y))+geom_raster(aes(fill=log1p(z)))+scale_fill_continuous(low="red",high="blue")+theme_classic()
(base_plot<-ggplot(pd)+geom_contour(aes(x=x,y=y,z=log1p(z),colour=..level..))+scale_colour_continuous(low="red",high="blue")+geom_point(data=solution,aes(x,y),colour="red",size=10,shape="x")+theme_bw()+coord_cartesian(xlim=c(xlo,xhi),ylim=c(ylo,yhi)))
ggs("rosenbrock")
```

built-in solver nloptr L-BFGS

```{r}
res[["nloptr"]]<-nloptr_lbfgs(rosenbrock_f,rosenbrock_g,c(3,5))
base_plot+geom_path(aes(x=x,y=y),data=res$nloptr)
```

simple gradient descent

```{r}
res<-list()
res[["gd"]]<-grad_descent(rosenbrock_f,rosenbrock_g,c(3,5))
base_plot+geom_path(aes(x=x,y=y),data=res$gd)
ggs("gd")
```

gradient descent with momentum

```{r}
res[["mtm"]]<-momentum(rosenbrock_f,rosenbrock_g,c(3,5),stp=.002)
base_plot+geom_path(data=res$mtm,aes(x,y))
ggs("mtm")
```

gradient descent with Nesterov momentum

```{r}
res[["nstv"]]<-nesterov(rosenbrock_f,rosenbrock_g,c(3,5),stp=.002)
base_plot+geom_path(data=res$nstv,aes(x,y))
ggs("nstv")
```

improved rprop

```{r}
res[["irprop"]]<-irprop(rosenbrock_f,rosenbrock_g,c(3,5))
base_plot+geom_path(data=res$irprop,aes(x,y))
#with(tail(res$irprop,20),plot(x,y,type="l"))
```

adamax- Adam with infinity norm

```{r}
res[["admx"]]<-adamax(rosenbrock_f,rosenbrock_g,c(3,5),stp=3)
base_plot+geom_path(data=res$admx,aes(x,y))
#with(tail(res$admx,500),plot(x,y,type="l"))
ggs("admx")
```

nadam- Adam with nesterov momentum

```{r}
res[["nadm"]]<-nadam(rosenbrock_f,rosenbrock_g,c(3,5),stp=3)
base_plot+geom_path(data=res$nadm,aes(x,y))
#with(tail(res$admx,500),plot(x,y,type="l"))
ggs("nadm")
```

avagrad

```{r}
res[["avagrad"]]<-avagrad(rosenbrock_f,rosenbrock_g,c(3,5),stp=.1,adam_eps_param =.1)
base_plot+geom_path(data=res$avagrad,aes(x,y))
ggs("avagrad")
```

Newton-Raphson with full hessian

```{r}
res[["newton_full"]]<-newton_full(rosenbrock_f,rosenbrock_g,rosenbrock_h,c(3,5))
base_plot+geom_path(aes(x=x,y=y),data=res$newton_full)
ggs("newton_full")
```

Approximate Newton-Raphson with diagonal hessian

```{r}
res[["newton_diag"]]<-newton_diag(rosenbrock_f,rosenbrock_g,rosenbrock_h,c(3,5),stp=.95)
base_plot+geom_path(aes(x=x,y=y),data=res$newton_diag)
ggs("newton_diag")
```

summary of results

```{r}
pd2<-data.frame(method=names(res),nSteps=sapply(res,nrow))
pd2$err<-sapply(res,function(x){x[nrow(x),3]})
pd2$method<-factor(pd2$method,levels=pd2$method[order(pd2$err)])
ggplot(pd2)+geom_bar(aes(x=method,y=err),stat="identity")
#bad<-pd2$err>1e-3
ggplot(subset(pd2,err<1e-3))+geom_bar(aes(x=method,y=err),stat="identity")
pd2$method<-factor(pd2$method,levels=pd2$method[order(pd2$nSteps)])
ggplot(pd2)+geom_bar(aes(x=method,y=nSteps),stat="identity")
```